// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coder/agentapi/lib/screentracker (interfaces: ConversationTracker,AgentIO)
//
// Generated by this command:
//
//	mockgen -destination=mock_conversation_tracker_test.go -package=screentracker . ConversationTracker,AgentIO
//

// Package screentracker is a generated GoMock package.
package screentracker

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConversationTracker is a mock of ConversationTracker interface.
type MockConversationTracker struct {
	ctrl     *gomock.Controller
	recorder *MockConversationTrackerMockRecorder
	isgomock struct{}
}

// MockConversationTrackerMockRecorder is the mock recorder for MockConversationTracker.
type MockConversationTrackerMockRecorder struct {
	mock *MockConversationTracker
}

// NewMockConversationTracker creates a new mock instance.
func NewMockConversationTracker(ctrl *gomock.Controller) *MockConversationTracker {
	mock := &MockConversationTracker{ctrl: ctrl}
	mock.recorder = &MockConversationTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationTracker) EXPECT() *MockConversationTrackerMockRecorder {
	return m.recorder
}

// GetInitialPrompt mocks base method.
func (m *MockConversationTracker) GetInitialPrompt() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInitialPrompt")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetInitialPrompt indicates an expected call of GetInitialPrompt.
func (mr *MockConversationTrackerMockRecorder) GetInitialPrompt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInitialPrompt", reflect.TypeOf((*MockConversationTracker)(nil).GetInitialPrompt))
}

// IsInitialPromptSent mocks base method.
func (m *MockConversationTracker) IsInitialPromptSent() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInitialPromptSent")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInitialPromptSent indicates an expected call of IsInitialPromptSent.
func (mr *MockConversationTrackerMockRecorder) IsInitialPromptSent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInitialPromptSent", reflect.TypeOf((*MockConversationTracker)(nil).IsInitialPromptSent))
}

// IsReadyForInitialPrompt mocks base method.
func (m *MockConversationTracker) IsReadyForInitialPrompt() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReadyForInitialPrompt")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReadyForInitialPrompt indicates an expected call of IsReadyForInitialPrompt.
func (mr *MockConversationTrackerMockRecorder) IsReadyForInitialPrompt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReadyForInitialPrompt", reflect.TypeOf((*MockConversationTracker)(nil).IsReadyForInitialPrompt))
}

// Messages mocks base method.
func (m *MockConversationTracker) Messages() []ConversationMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Messages")
	ret0, _ := ret[0].([]ConversationMessage)
	return ret0
}

// Messages indicates an expected call of Messages.
func (mr *MockConversationTrackerMockRecorder) Messages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Messages", reflect.TypeOf((*MockConversationTracker)(nil).Messages))
}

// Screen mocks base method.
func (m *MockConversationTracker) Screen() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Screen")
	ret0, _ := ret[0].(string)
	return ret0
}

// Screen indicates an expected call of Screen.
func (mr *MockConversationTrackerMockRecorder) Screen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Screen", reflect.TypeOf((*MockConversationTracker)(nil).Screen))
}

// SendMessage mocks base method.
func (m *MockConversationTracker) SendMessage(messageParts ...MessagePart) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range messageParts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendMessage", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockConversationTrackerMockRecorder) SendMessage(messageParts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockConversationTracker)(nil).SendMessage), messageParts...)
}

// SetInitialPromptSent mocks base method.
func (m *MockConversationTracker) SetInitialPromptSent(sent bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetInitialPromptSent", sent)
}

// SetInitialPromptSent indicates an expected call of SetInitialPromptSent.
func (mr *MockConversationTrackerMockRecorder) SetInitialPromptSent(sent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInitialPromptSent", reflect.TypeOf((*MockConversationTracker)(nil).SetInitialPromptSent), sent)
}

// SetReadyForInitialPrompt mocks base method.
func (m *MockConversationTracker) SetReadyForInitialPrompt(ready bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetReadyForInitialPrompt", ready)
}

// SetReadyForInitialPrompt indicates an expected call of SetReadyForInitialPrompt.
func (mr *MockConversationTrackerMockRecorder) SetReadyForInitialPrompt(ready any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReadyForInitialPrompt", reflect.TypeOf((*MockConversationTracker)(nil).SetReadyForInitialPrompt), ready)
}

// StartSnapshotLoop mocks base method.
func (m *MockConversationTracker) StartSnapshotLoop(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartSnapshotLoop", ctx)
}

// StartSnapshotLoop indicates an expected call of StartSnapshotLoop.
func (mr *MockConversationTrackerMockRecorder) StartSnapshotLoop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSnapshotLoop", reflect.TypeOf((*MockConversationTracker)(nil).StartSnapshotLoop), ctx)
}

// Status mocks base method.
func (m *MockConversationTracker) Status() ConversationStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(ConversationStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockConversationTrackerMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockConversationTracker)(nil).Status))
}

// MockAgentIO is a mock of AgentIO interface.
type MockAgentIO struct {
	ctrl     *gomock.Controller
	recorder *MockAgentIOMockRecorder
	isgomock struct{}
}

// MockAgentIOMockRecorder is the mock recorder for MockAgentIO.
type MockAgentIOMockRecorder struct {
	mock *MockAgentIO
}

// NewMockAgentIO creates a new mock instance.
func NewMockAgentIO(ctrl *gomock.Controller) *MockAgentIO {
	mock := &MockAgentIO{ctrl: ctrl}
	mock.recorder = &MockAgentIOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentIO) EXPECT() *MockAgentIOMockRecorder {
	return m.recorder
}

// ReadScreen mocks base method.
func (m *MockAgentIO) ReadScreen() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadScreen")
	ret0, _ := ret[0].(string)
	return ret0
}

// ReadScreen indicates an expected call of ReadScreen.
func (mr *MockAgentIOMockRecorder) ReadScreen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadScreen", reflect.TypeOf((*MockAgentIO)(nil).ReadScreen))
}

// Write mocks base method.
func (m *MockAgentIO) Write(data []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockAgentIOMockRecorder) Write(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockAgentIO)(nil).Write), data)
}
