version: "2"
linters:
  enable:
    - exhaustive
  settings:
    exhaustive:
      default-signifies-exhaustive: true
      check:
        - "switch"
        - "map"
    staticcheck:
      checks:
        - "-QF1001" # disable "could apply De Morgan's law"
