name: Fuzzing

permissions:
  contents: read

on:
  push:
    paths:
      - '**.rs'
      - '**.go'
  schedule:
    - cron: '0 0 * * *'

jobs:
  cargo-fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz || true
      - name: Run fuzzing
        run: cargo fuzz run all || true
        continue-on-error: true
